#!/usr/bin/env python3
"""
disaster-playbook.py — generate a stack-specific incident-response runbook.

Detects which platforms your project uses (Supabase, Stripe, Vercel, Auth0,
Clerk, AWS, etc.), then writes a markdown file with the EXACT commands and
URLs you'll need if you get hacked tomorrow. Stops the panic-google moment.

Usage:
  python3 scripts/disaster-playbook.py                    # auto-detect, write DISASTER.md
  python3 scripts/disaster-playbook.py --output runbook.md
  python3 scripts/disaster-playbook.py --stack supabase,stripe,vercel
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

# Each section returns markdown content. They're parameterised by detected info
# where possible (project ID, env names, etc.).

def section_intro() -> str:
    return """# 🚨 Disaster Recovery Playbook

Generated by `agentic-security`. If you're reading this BECAUSE something bad
happened, breathe, then follow the relevant section. If you're reading this
preemptively (good): bookmark this file and re-generate it whenever your
stack changes.

## The first 10 minutes — universal triage

1. **Stop the bleeding.** If you can shut down the affected service, do it:
   - Vercel: `vercel domains inspect <domain>` → `vercel rollback`
   - Fly: `fly scale count 0 --app <app>` (instant shutdown)
   - Railway: dashboard → Settings → "Pause service"
   - Cloudflare Worker: dashboard → Workers → Triggers → disable
2. **Rotate every credential** in `.env*` files (use `/rotate-key-auto --scan`).
3. **Take a snapshot** of the current DB state before doing anything else:
   ```
   pg_dump $DATABASE_URL > "evidence_$(date +%s).sql"
   ```
4. **Save your logs** before they roll off:
   - Vercel:  `vercel logs --since 24h > evidence_logs.txt`
   - Fly:     `fly logs --since 24h > evidence_logs.txt`
   - Supabase: dashboard → Logs → download
5. **Take screenshots** of everything anomalous — dashboards, error pages, weird user records.

---
"""


def section_supabase() -> str:
    return """## Supabase incident response

### Service-role key leaked

```bash
# 1. Rotate the JWT secret (invalidates ALL tokens, anon AND service-role)
# In dashboard: Settings → API → "Generate new JWT secret"

# 2. Find every server that uses the old key:
grep -rn SUPABASE_SERVICE_ROLE_KEY .

# 3. Update env vars in your deployment platform:
vercel env rm SUPABASE_SERVICE_ROLE_KEY production
vercel env add SUPABASE_SERVICE_ROLE_KEY production
# (paste new value)

# 4. Force-rotate all users' refresh tokens:
psql $DATABASE_URL -c "DELETE FROM auth.refresh_tokens;"
```

### Suspected unauthorized DB writes

```bash
# 1. Identify all table mutations in the last 24h:
psql $DATABASE_URL -c "
  SELECT schemaname, relname, n_tup_ins, n_tup_upd, n_tup_del
  FROM pg_stat_user_tables ORDER BY (n_tup_ins + n_tup_upd + n_tup_del) DESC LIMIT 20;
"

# 2. Restore from PITR (Point-in-Time Recovery) — paid plans only:
# Dashboard → Database → "Point in Time Recovery" → pick timestamp before incident

# 3. Audit your RLS policies — leaks usually start here:
psql $DATABASE_URL -c "
  SELECT schemaname, tablename, policyname, cmd, qual
  FROM pg_policies ORDER BY schemaname, tablename;
"

# 4. Force every user to re-authenticate:
psql $DATABASE_URL -c "DELETE FROM auth.refresh_tokens;"
```

### Suspected RLS bypass

If you can't tell whether RLS was bypassed:

```sql
-- Run on a SUSPECTED-COMPROMISED row to see who could have read it:
SELECT * FROM <your-table> WHERE id = '<row>'
  -- if this row returned from an anon JWT it's a bypass.

-- Audit every table's RLS:
SELECT relname, relrowsecurity, relforcerowsecurity
  FROM pg_class WHERE relkind = 'r' AND relnamespace = 'public'::regnamespace;
-- relrowsecurity = false → RLS not enabled on that table
```

### Useful URLs

- API keys & JWT secret rotation: https://supabase.com/dashboard/project/_/settings/api
- Database backups: https://supabase.com/dashboard/project/_/database/backups
- Logs: https://supabase.com/dashboard/project/_/logs

---
"""


def section_stripe() -> str:
    return """## Stripe incident response

### Live secret key (`sk_live_...`) leaked

```bash
# 1. Roll the key NOW — every minute matters:
# Dashboard → https://dashboard.stripe.com/apikeys → "Roll key" next to leaked key

# Or via CLI (requires `stripe login`):
stripe keys create --type restricted_key --name "rotated-$(date +%Y%m%d)"

# 2. Audit recent activity for unauthorised charges/refunds:
stripe charges list --created.gte $(date -v-1d +%s) --limit 100
stripe refunds list --created.gte $(date -v-1d +%s) --limit 100
stripe payouts list --created.gte $(date -v-1d +%s) --limit 100

# 3. Lock down restricted keys to least privilege:
# Dashboard → API keys → "Create restricted key" → grant only the scopes you need
```

### Webhook secret (`whsec_...`) leaked

```bash
# 1. Rotate in dashboard:
# https://dashboard.stripe.com/webhooks → endpoint → "Click to reveal" → "Roll secret"

# 2. Update your env:
# STRIPE_WEBHOOK_SECRET=whsec_NEW...

# 3. Re-send failed events that came in during the rotation gap:
# Dashboard → Webhooks → endpoint → "Events" → filter "Pending" → resend
```

### Fraudulent charges detected

1. Dispute the charges yourself before customers do — go to the Payments view and refund the obvious fraud. Customer-initiated disputes hurt your dispute rate.
2. Enable Radar rules: `Stripe → Settings → Radar → Rules` — add at minimum:
   - Block if `card_country` ≠ `billing_country`
   - Review if `email_risk_level` is `high`
3. If volume is high, contact Stripe support directly. They can freeze pending payouts and help with the cleanup.

### Useful URLs

- API keys: https://dashboard.stripe.com/apikeys
- Webhooks: https://dashboard.stripe.com/webhooks
- Radar: https://dashboard.stripe.com/settings/radar

---
"""


def section_vercel() -> str:
    return """## Vercel incident response

### Bad deploy reached prod

```bash
# Instant rollback:
vercel rollback                        # rolls to the previous prod deploy

# Or pick a specific deploy to promote:
vercel ls                              # list recent deploys
vercel promote <deployment-url>        # promote a known-good preview to prod
```

### Build pulled a malicious / compromised dependency

```bash
# 1. Pause auto-deploys to prevent the bad commit going out again:
# Dashboard → Project → Settings → Git → "Ignored Build Step" → echo 'pause' → exit 1

# 2. Re-deploy a known-good SHA:
vercel deploy --prod --commit <known-good-sha>

# 3. Audit your lockfile for the malicious package — pin it out:
npm ls <suspect-package>
npm uninstall <suspect-package>
# or pin via package.json "overrides"
```

### Function exceeding budget

```bash
# Find the offender:
vercel logs --since 24h | grep -i "duration\\|invocation"

# Pause the function temporarily:
# Dashboard → Functions → <name> → "Disable"

# Move to a different region or runtime if appropriate.
```

### Useful URLs

- Deployments: `https://vercel.com/<team>/<project>/deployments`
- Logs: `https://vercel.com/<team>/<project>/logs`
- Env vars: `https://vercel.com/<team>/<project>/settings/environment-variables`

---
"""


def section_stripe_provider() -> str:
    # already covered above
    return ""


def section_auth0() -> str:
    return """## Auth0 incident response

### Session token / refresh token leaked

```bash
# 1. Invalidate all sessions for the affected user:
# Dashboard → User Management → Users → select user → "Sign Out" / "Block User"

# 2. Force every user to re-authenticate (nuclear):
# Dashboard → Tenant Settings → Advanced → "Revoke all refresh tokens"

# 3. Rotate the application's client secret:
# Applications → <app> → Settings → "Rotate" (under Client Secret)
```

### Useful URLs

- Tenant settings: https://manage.auth0.com/dashboard
- Logs (live): https://manage.auth0.com/#/logs

---
"""


def section_clerk() -> str:
    return """## Clerk incident response

### Session compromise / token leaked

```bash
# 1. Force all sessions to expire:
# Dashboard → Sessions → "Revoke all" (per-user) or instance-wide via API

# 2. Rotate the secret key:
# Dashboard → API Keys → "Roll secret key" → update CLERK_SECRET_KEY env

# 3. If publishable key is compromised, it doesn't grant access on its own,
#    but rotate it anyway and audit any backend keys with the same prefix family.
```

### Webhook signing secret leaked

```bash
# Dashboard → Webhooks → endpoint → "Rotate signing secret"
# Update CLERK_WEBHOOK_SECRET in your env.
```

### Useful URLs

- API keys: https://dashboard.clerk.com/apps/_/instances/_/api-keys
- Sessions: https://dashboard.clerk.com/apps/_/instances/_/sessions

---
"""


def section_aws() -> str:
    return """## AWS incident response

### IAM access key (`AKIA...`) leaked

```bash
# 1. Disable the key IMMEDIATELY (don't wait to find the user — just disable):
aws iam list-access-keys --user-name <USER>     # if you know the user
aws iam update-access-key --access-key-id <KEY> --status Inactive --user-name <USER>

# 2. If you DON'T know which user the key belongs to, find it:
aws iam list-users | jq -r '.Users[].UserName' | while read u; do
  aws iam list-access-keys --user-name "$u" | grep <KEY-PREFIX> && echo "FOUND user: $u"
done

# 3. Once disabled, delete and replace:
aws iam delete-access-key --access-key-id <KEY> --user-name <USER>
aws iam create-access-key --user-name <USER>

# 4. Check for crypto-mining instances spun up with the leaked key:
aws ec2 describe-instances --query 'Reservations[*].Instances[?LaunchTime>=`'$(date -v-3d +%Y-%m-%d)'`].[InstanceId,InstanceType,LaunchTime]' --output table
# Look for unusually large instance types you didn't launch (p3, g4dn, p4d).

# 5. Audit billing:
# Console → Billing → Cost Explorer → group by Service, filter to last 3 days
```

### S3 bucket exposed publicly

```bash
# 1. Block public access immediately:
aws s3api put-public-access-block --bucket <BUCKET> --public-access-block-configuration \\
  BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true

# 2. Audit who accessed it during exposure (if access logging is enabled):
aws s3 cp s3://<LOG-BUCKET>/<LOG-PREFIX>/ ./logs/ --recursive

# 3. Enable bucket versioning so future accidents are recoverable:
aws s3api put-bucket-versioning --bucket <BUCKET> --versioning-configuration Status=Enabled
```

### Useful URLs

- IAM: https://console.aws.amazon.com/iam/home#/users
- Cost Explorer: https://console.aws.amazon.com/cost-management/home
- GuardDuty (free for 30d): https://console.aws.amazon.com/guardduty/home

---
"""


def section_npm() -> str:
    return """## npm supply-chain incident

### Malicious / compromised dependency detected

```bash
# 1. Find every place the package is installed (incl. transitively):
npm ls <suspect-package>

# 2. Pin it OUT via package.json "overrides":
# Edit package.json:
#   "overrides": { "<suspect-package>": "npm:noop-package@1.0.0" }
# (or pin to a known-good version)

# 3. Rebuild from scratch:
rm -rf node_modules package-lock.json
npm install

# 4. Audit install scripts in your tree (the primary supply-chain vector):
npm ls --all --parseable | xargs -I {} sh -c 'jq -r .scripts {}/package.json 2>/dev/null | grep -l "postinstall\\|preinstall\\|install" && echo "  ↑ {}"'

# 5. Rotate every credential the install scripts might have read:
#    .npmrc tokens, AWS env vars, .env files, ~/.aws/credentials
```

### Postinstall script may have exfiltrated secrets

Assume the worst:
1. Rotate ALL credentials accessible from the machine that ran `npm install`.
2. Inspect outbound network from that machine for anomalies.
3. If on CI, rotate the CI's tokens (GitHub Actions, CircleCI, etc.).

---
"""


def section_universal_close() -> str:
    return """## After the immediate fire is out

### Disclose

If user data was involved, GDPR Article 33 gives you **72 hours** to notify the supervisory authority. Many other jurisdictions have similar windows. Don't sit on it.

- Draft a customer notification — explain *what happened*, *what data*, *what they should do*, *what you're doing*.
- Update your status page.
- Send the notification before press finds out.

### Postmortem

Write the postmortem within 7 days while the details are fresh:
- What was the entry point?
- What detection signal *should* have fired earlier?
- What's the patch that ensures this exact thing can't happen again?
- What patch would prevent the *class* of bug (not just this instance)?

Save it in `docs/postmortems/YYYY-MM-DD-<title>.md`.

### Replay regression tests

Once patched, write a regression test for the exact attack — `/validate-findings` and `/run-poc-tests.py --verify-fix` will keep it from coming back.

---

*Generated by `agentic-security`. Re-run `/disaster-playbook` whenever your stack changes.*
"""


# ─────────────────────────────────────────────────────────────────────────────
# Stack detection
# ─────────────────────────────────────────────────────────────────────────────

def detect_stack(cwd: Path) -> set[str]:
    stack = set()
    # File markers
    if (cwd / "vercel.json").exists() or (cwd / ".vercel").exists():
        stack.add("vercel")
    if (cwd / "fly.toml").exists():
        stack.add("fly")
    if (cwd / "supabase" / "config.toml").exists() or any(cwd.rglob("supabase/migrations/*.sql")):
        stack.add("supabase")
    # Package.json deps
    pkg = cwd / "package.json"
    if pkg.exists():
        try:
            data = json.loads(pkg.read_text())
            deps = {**data.get("dependencies", {}), **data.get("devDependencies", {})}
            if "stripe" in deps or "@stripe/stripe-js" in deps:
                stack.add("stripe")
            if "@supabase/supabase-js" in deps or "@supabase/ssr" in deps:
                stack.add("supabase")
            if "@clerk/nextjs" in deps or "@clerk/clerk-react" in deps or "@clerk/clerk-sdk-node" in deps:
                stack.add("clerk")
            if "@auth0/nextjs-auth0" in deps or "auth0" in deps:
                stack.add("auth0")
            if "aws-sdk" in deps or "@aws-sdk/client-s3" in deps:
                stack.add("aws")
            stack.add("npm")  # always include npm advice if package.json present
        except Exception:
            pass
    # Env file hints
    for env_name in (".env", ".env.local", ".env.production", ".env.example"):
        ep = cwd / env_name
        if ep.exists():
            try:
                content = ep.read_text(errors="ignore")
                if "STRIPE_" in content: stack.add("stripe")
                if "SUPABASE_" in content: stack.add("supabase")
                if "CLERK_" in content: stack.add("clerk")
                if "AUTH0_" in content: stack.add("auth0")
                if "AWS_" in content: stack.add("aws")
            except Exception:
                pass
    return stack


SECTION_BUILDERS = {
    "supabase": section_supabase,
    "stripe":   section_stripe,
    "vercel":   section_vercel,
    "auth0":    section_auth0,
    "clerk":    section_clerk,
    "aws":      section_aws,
    "npm":      section_npm,
}


def build_playbook(stack: set[str]) -> str:
    parts = [section_intro()]
    # Order: hosting first, then auth, then payment, then cloud, then npm
    order = ["vercel", "fly", "supabase", "auth0", "clerk", "stripe", "aws", "npm"]
    for name in order:
        if name in stack and name in SECTION_BUILDERS:
            parts.append(SECTION_BUILDERS[name]())
    if not any(s in stack for s in SECTION_BUILDERS):
        parts.append("## Stack not detected\n\nNo recognised platforms found. Universal triage above still applies.\n\n---\n")
    parts.append(section_universal_close())
    return "".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a stack-specific disaster recovery playbook.")
    parser.add_argument("--cwd", default=None)
    parser.add_argument("--output", default="DISASTER.md")
    parser.add_argument("--stack", default=None,
                        help="Comma-separated stack names (skip detection)")
    parser.add_argument("--print", action="store_true",
                        help="Print to stdout instead of writing a file")
    args = parser.parse_args()

    cwd = Path(args.cwd).resolve() if args.cwd else Path.cwd()
    if args.stack:
        stack = {s.strip() for s in args.stack.split(",") if s.strip()}
    else:
        stack = detect_stack(cwd)

    md = build_playbook(stack)

    if args.print:
        print(md)
        return

    out = cwd / args.output
    out.write_text(md)
    print(f"✓ Disaster playbook written: {out.relative_to(cwd) if str(out).startswith(str(cwd)) else out}")
    print(f"  Stack detected: {', '.join(sorted(stack)) or '(none)'}")
    print(f"  Bookmark it. Re-run when your stack changes.")


if __name__ == "__main__":
    main()
