#!/usr/bin/env python3
"""
trust-page.py — generate /.well-known/security.txt and a /security page
                that displays your live security posture.

Buyers and infosec teams look for these. Most vibe-coded apps have
neither. This script writes:

  public/.well-known/security.txt          (or static/, depending on stack)
  app/security/page.tsx                    (Next.js App Router)
  src/pages/security.tsx                   (Next.js Pages Router)
  public/security/index.html               (vanilla)

Plus a JSON dump of the live posture (counts, streak, last-scan time) that
the /security page reads at build time.

Usage:
  python3 scripts/trust-page.py --contact security@myapp.com
  python3 scripts/trust-page.py --contact security@myapp.com --pgp keys.example.com/foo.asc
"""

from __future__ import annotations

import argparse
import json
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path


def detect_stack(cwd: Path) -> dict:
    """Return paths to where security.txt and security page should land."""
    out = {
        "public": cwd / "public",
        "app_router": cwd / "app",
        "pages_router": cwd / "src" / "pages",
        "framework": "unknown",
    }
    pkg = cwd / "package.json"
    if pkg.exists():
        try:
            data = json.loads(pkg.read_text())
            deps = {**data.get("dependencies", {}), **data.get("devDependencies", {})}
            if "next" in deps:
                out["framework"] = "next-app" if (cwd / "app").exists() else "next-pages"
            elif "vite" in deps or "react" in deps:
                out["framework"] = "vite-react"
                out["public"] = cwd / "public"
            elif "remix" in deps or "@remix-run/node" in deps:
                out["framework"] = "remix"
                out["public"] = cwd / "public"
        except Exception:
            pass
    if (cwd / "static").exists() and not (cwd / "public").exists():
        out["public"] = cwd / "static"
    return out


def render_security_txt(contact: str, pgp_url: str | None, canonical_url: str | None) -> str:
    expires = (datetime.now(timezone.utc) + timedelta(days=365)).strftime("%Y-%m-%dT%H:%M:%S.000Z")
    lines = [
        f"Contact: mailto:{contact}",
        f"Expires: {expires}",
        "Preferred-Languages: en",
    ]
    if pgp_url:
        lines.append(f"Encryption: {pgp_url}")
    if canonical_url:
        lines.append(f"Canonical: {canonical_url}/.well-known/security.txt")
    lines.append("Policy: " + (canonical_url + "/security" if canonical_url else "https://example.com/security"))
    lines.append("")
    lines.append("# Generated by agentic-security. Re-run /trust-page to refresh the Expires date.")
    return "\n".join(lines) + "\n"


def render_posture_json(cwd: Path) -> dict:
    scan = {}
    try:
        scan = json.loads((cwd / ".agentic-security" / "last-scan.json").read_text())
    except Exception:
        pass
    streak = {}
    try:
        streak = json.loads((cwd / ".agentic-security" / "streak.json").read_text())
    except Exception:
        pass
    findings = []
    for k in ("findings", "logicVulns", "supplyChain"):
        findings.extend(scan.get(k, []))
    counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}
    for f in findings:
        sev = (f.get("severity") or "low").lower()
        counts[sev] = counts.get(sev, 0) + 1
    return {
        "lastScan": scan.get("startedAt") or scan.get("scanId") or "never",
        "counts": counts,
        "streakDays": streak.get("days", 0),
        "generatedAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }


def render_next_app_page(contact: str, posture: dict) -> str:
    return f"""// agentic-security: auto-generated /security page
// Renders live posture from public/security-posture.json.

import {{ readFileSync }} from 'node:fs';
import {{ join }} from 'node:path';

export const metadata = {{
  title: 'Security',
  description: 'Our security posture, contact, and reporting policy.',
}};

function loadPosture() {{
  try {{
    const raw = readFileSync(join(process.cwd(), 'public', 'security-posture.json'), 'utf8');
    return JSON.parse(raw);
  }} catch {{ return null; }}
}}

export default function SecurityPage() {{
  const posture = loadPosture();
  const counts = posture?.counts || {{}};
  const totalCrit = (counts.critical || 0) + (counts.high || 0);
  const state = totalCrit === 0 ? '✅ Green' : (counts.critical === 0 ? '🟡 Yellow' : '🔴 Red');

  return (
    <main style={{{{ maxWidth: 760, margin: '64px auto', padding: 24, fontFamily: 'system-ui, sans-serif', lineHeight: 1.6 }}}}>
      <h1>Security</h1>
      <p>We take application security seriously. This page is generated from
      our live security tooling and updates on every build.</p>

      <h2>Current posture</h2>
      <div style={{{{ display: 'flex', gap: 12, alignItems: 'baseline', marginBottom: 12 }}}}>
        <strong style={{{{ fontSize: 24 }}}}>{{state}}</strong>
        {{posture?.streakDays > 0 && (
          <span style={{{{ color: '#475569' }}}}>{{posture.streakDays}}-day clean streak</span>
        )}}
      </div>
      <table style={{{{ borderCollapse: 'collapse', marginBottom: 32 }}}}>
        <tbody>
          <tr><td style={{{{ padding: 4, color: '#475569' }}}}>Critical findings</td><td style={{{{ padding: 4 }}}}>{{counts.critical || 0}}</td></tr>
          <tr><td style={{{{ padding: 4, color: '#475569' }}}}>High findings</td><td style={{{{ padding: 4 }}}}>{{counts.high || 0}}</td></tr>
          <tr><td style={{{{ padding: 4, color: '#475569' }}}}>Medium findings</td><td style={{{{ padding: 4 }}}}>{{counts.medium || 0}}</td></tr>
          <tr><td style={{{{ padding: 4, color: '#475569' }}}}>Last scan</td><td style={{{{ padding: 4 }}}}>{{posture?.lastScan || 'unknown'}}</td></tr>
        </tbody>
      </table>

      <h2>Practices</h2>
      <ul>
        <li>Continuous static analysis on every code change (OWASP Top 10, LLM Top 10, 30+ vuln classes)</li>
        <li>Dependency monitoring against OSV and CISA KEV</li>
        <li>Encryption in transit (TLS 1.2+) and at rest (AES-256)</li>
        <li>Principle of least access for production credentials</li>
        <li>72-hour breach notification commitment (GDPR Art. 33)</li>
      </ul>

      <h2>Report a security issue</h2>
      <p>Email <a href="mailto:{contact}">{contact}</a>. We commit to:</p>
      <ul>
        <li>Acknowledge within <strong>24 hours</strong></li>
        <li>Provide an initial assessment within <strong>72 hours</strong></li>
        <li>Patch confirmed critical issues within <strong>7 days</strong></li>
      </ul>
      <p>Our authoritative contact is published at <a href="/.well-known/security.txt"><code>/.well-known/security.txt</code></a>.</p>

      <h2>Related</h2>
      <ul>
        <li><a href="/privacy">Privacy policy</a></li>
        <li><a href="/.well-known/security.txt">security.txt</a></li>
      </ul>

      <hr style={{{{ marginTop: 48, borderColor: '#e2e8f0' }}}} />
      <p style={{{{ color: '#94a3b8', fontSize: 12 }}}}>Generated by agentic-security on {{posture?.generatedAt || 'unknown'}}.</p>
    </main>
  );
}}
"""


def render_vanilla_html(contact: str, posture: dict) -> str:
    counts = posture.get("counts", {})
    crit = counts.get("critical", 0)
    high = counts.get("high", 0)
    state = "✅ Green" if (crit + high) == 0 else "🟡 Yellow" if crit == 0 else "🔴 Red"
    streak_html = f"<span style='color:#475569'>{posture.get('streakDays', 0)}-day clean streak</span>" if posture.get("streakDays", 0) > 0 else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Security</title>
<style>
  body {{ max-width: 760px; margin: 64px auto; padding: 24px; font-family: system-ui, sans-serif; line-height: 1.6; }}
  table {{ border-collapse: collapse; margin-bottom: 32px; }}
  td {{ padding: 4px 12px 4px 0; }}
  td.label {{ color: #475569; }}
  hr {{ margin-top: 48px; border: none; border-top: 1px solid #e2e8f0; }}
  footer {{ color: #94a3b8; font-size: 12px; }}
</style>
</head>
<body>
<h1>Security</h1>
<p>We take application security seriously. This page reflects our live security posture.</p>

<h2>Current posture</h2>
<div style="display:flex;gap:12px;align-items:baseline;margin-bottom:12px;">
  <strong style="font-size:24px;">{state}</strong>
  {streak_html}
</div>
<table>
<tr><td class="label">Critical findings</td><td>{counts.get('critical', 0)}</td></tr>
<tr><td class="label">High findings</td><td>{counts.get('high', 0)}</td></tr>
<tr><td class="label">Medium findings</td><td>{counts.get('medium', 0)}</td></tr>
<tr><td class="label">Last scan</td><td>{posture.get('lastScan', 'unknown')}</td></tr>
</table>

<h2>Practices</h2>
<ul>
  <li>Continuous static analysis on every code change (OWASP Top 10, LLM Top 10)</li>
  <li>Dependency monitoring against OSV and CISA KEV</li>
  <li>Encryption in transit (TLS 1.2+) and at rest (AES-256)</li>
  <li>Principle of least access for production credentials</li>
  <li>72-hour breach notification commitment (GDPR Art. 33)</li>
</ul>

<h2>Report a security issue</h2>
<p>Email <a href="mailto:{contact}">{contact}</a>. Authoritative contact: <a href="/.well-known/security.txt">/.well-known/security.txt</a>.</p>

<hr>
<footer>Generated by agentic-security on {posture.get('generatedAt', 'unknown')}.</footer>
</body>
</html>
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate /.well-known/security.txt and a /security page.")
    parser.add_argument("--cwd", default=None)
    parser.add_argument("--contact", required=True, help="Security contact email")
    parser.add_argument("--pgp", default=None, help="Public PGP key URL (optional)")
    parser.add_argument("--canonical-url", default=None, help="Canonical app URL (https://yourapp.com)")
    args = parser.parse_args()

    cwd = Path(args.cwd).resolve() if args.cwd else Path.cwd()
    stack = detect_stack(cwd)

    # 1) security.txt
    pub = stack["public"]
    pub.mkdir(parents=True, exist_ok=True)
    well_known = pub / ".well-known"
    well_known.mkdir(exist_ok=True)
    sec_txt = render_security_txt(args.contact, args.pgp, args.canonical_url)
    (well_known / "security.txt").write_text(sec_txt)
    print(f"✓ Wrote: {well_known.relative_to(cwd)}/security.txt")

    # 2) Live posture JSON
    posture = render_posture_json(cwd)
    (pub / "security-posture.json").write_text(json.dumps(posture, indent=2))
    print(f"✓ Wrote: {pub.relative_to(cwd)}/security-posture.json")

    # 3) /security page tailored to framework
    if stack["framework"] == "next-app":
        page_dir = cwd / "app" / "security"
        page_dir.mkdir(parents=True, exist_ok=True)
        page = page_dir / "page.tsx"
        page.write_text(render_next_app_page(args.contact, posture))
        print(f"✓ Wrote: {page.relative_to(cwd)}")
    elif stack["framework"] == "next-pages":
        page_dir = cwd / "src" / "pages"
        page_dir.mkdir(parents=True, exist_ok=True)
        page = page_dir / "security.tsx"
        page.write_text(render_next_app_page(args.contact, posture))  # same shape works for pages router with minor tweaks
        print(f"✓ Wrote: {page.relative_to(cwd)}")
    else:
        # Vanilla HTML fallback
        sec_dir = pub / "security"
        sec_dir.mkdir(exist_ok=True)
        page = sec_dir / "index.html"
        page.write_text(render_vanilla_html(args.contact, posture))
        print(f"✓ Wrote: {page.relative_to(cwd)}")

    print()
    print(f"Framework detected:  {stack['framework']}")
    print(f"Posture snapshot:    {posture['counts'].get('critical', 0)} critical · "
          f"{posture['counts'].get('high', 0)} high · "
          f"streak={posture.get('streakDays', 0)}d")
    print()
    print("Next steps:")
    print(f"  1. Verify the URLs after deploy:")
    print(f"     - https://<yourdomain>/.well-known/security.txt")
    print(f"     - https://<yourdomain>/security")
    print(f"  2. Re-run /trust-page periodically — security.txt has a 1-year expiry.")
    print(f"  3. Run /security-onepager to generate the sales-deliverable counterpart.")


if __name__ == "__main__":
    main()
